var hierarchy =
[
    [ "mage::AABB", "classmage_1_1_a_a_b_b.html", null ],
    [ "mage::AAPass", "classmage_1_1_a_a_pass.html", null ],
    [ "mage::AlignedAllocator< DataT, AlignmentS >", "classmage_1_1_aligned_allocator.html", null ],
    [ "mage::MemoryArena::Allocator< DataT >", "classmage_1_1_memory_arena_1_1_allocator.html", null ],
    [ "mage::SingleEndedMemoryStack::Allocator< DataT >", "classmage_1_1_single_ended_memory_stack_1_1_allocator.html", null ],
    [ "mage::BackBufferPass", "classmage_1_1_back_buffer_pass.html", null ],
    [ "mage::BigEndianBinaryReader", "classmage_1_1_big_endian_binary_reader.html", [
      [ "mage::loader::MSHReader< VertexT, IndexT >", "classmage_1_1loader_1_1_m_s_h_reader.html", null ],
      [ "mage::loader::SpriteFontReader", "classmage_1_1loader_1_1_sprite_font_reader.html", null ]
    ] ],
    [ "mage::BigEndianBinaryWriter", "classmage_1_1_big_endian_binary_writer.html", [
      [ "mage::loader::MSHWriter< VertexT, IndexT >", "classmage_1_1loader_1_1_m_s_h_writer.html", null ]
    ] ],
    [ "mage::BinaryReader", "classmage_1_1_binary_reader.html", null ],
    [ "mage::BoundingFrustum", "classmage_1_1_bounding_frustum.html", null ],
    [ "mage::BoundingSphere", "classmage_1_1_bounding_sphere.html", null ],
    [ "mage::BoundingVolumePass", "classmage_1_1_bounding_volume_pass.html", null ],
    [ "mage::BufferLock", "classmage_1_1_buffer_lock.html", null ],
    [ "mage::CameraBuffer", "structmage_1_1_camera_buffer.html", null ],
    [ "mage::CameraLens", "classmage_1_1_camera_lens.html", null ],
    [ "mage::CameraSettings", "classmage_1_1_camera_settings.html", null ],
    [ "mage::ColorString", "classmage_1_1_color_string.html", null ],
    [ "mage::CompiledShader", "classmage_1_1_compiled_shader.html", [
      [ "mage::BlobCompiledShader", "classmage_1_1_blob_compiled_shader.html", null ],
      [ "mage::BufferCompiledShader", "classmage_1_1_buffer_compiled_shader.html", null ]
    ] ],
    [ "mage::Component", "classmage_1_1_component.html", [
      [ "mage::AmbientLight", "classmage_1_1_ambient_light.html", null ],
      [ "mage::BehaviorScript", "classmage_1_1_behavior_script.html", [
        [ "mage::script::CharacterMotorScript", "classmage_1_1script_1_1_character_motor_script.html", null ],
        [ "mage::script::EditorScript", "classmage_1_1script_1_1_editor_script.html", null ],
        [ "mage::script::ManhattanMotorScript", "classmage_1_1script_1_1_manhattan_motor_script.html", null ],
        [ "mage::script::MouseLookScript", "classmage_1_1script_1_1_mouse_look_script.html", null ],
        [ "mage::script::RotationScript", "classmage_1_1script_1_1_rotation_script.html", null ],
        [ "mage::script::StatsScript", "classmage_1_1script_1_1_stats_script.html", null ],
        [ "mage::script::SwitchSceneScript< SceneT >", "classmage_1_1script_1_1_switch_scene_script.html", null ],
        [ "mage::script::TextConsoleScript", "classmage_1_1script_1_1_text_console_script.html", null ]
      ] ],
      [ "mage::Camera", "classmage_1_1_camera.html", [
        [ "mage::OrthographicCamera", "classmage_1_1_orthographic_camera.html", null ],
        [ "mage::PerspectiveCamera", "classmage_1_1_perspective_camera.html", null ]
      ] ],
      [ "mage::DirectionalLight", "classmage_1_1_directional_light.html", null ],
      [ "mage::Model", "classmage_1_1_model.html", null ],
      [ "mage::OmniLight", "classmage_1_1_omni_light.html", null ],
      [ "mage::SpotLight", "classmage_1_1_spot_light.html", null ],
      [ "mage::SpriteImage", "classmage_1_1_sprite_image.html", null ],
      [ "mage::SpriteText", "classmage_1_1_sprite_text.html", null ]
    ] ],
    [ "mage::ComponentClient", "classmage_1_1_component_client.html", null ],
    [ "mage::ConstantBuffer< DataT >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::CameraBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::GameBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::LightBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::ModelBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::ModelNormalTextureTransformBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::ModelNormalTransformBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::ModelTextureTransformBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::RGBA >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< XMMATRIX >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< XMVECTOR >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantComponentPass", "classmage_1_1_constant_component_pass.html", null ],
    [ "mage::ConstantShadingPass", "classmage_1_1_constant_shading_pass.html", null ],
    [ "mage::CoreClock", "structmage_1_1_core_clock.html", null ],
    [ "mage::CoreClockPerCore", "structmage_1_1_core_clock_per_core.html", null ],
    [ "mage::CPUMonitor", "classmage_1_1_c_p_u_monitor.html", null ],
    [ "mage::Pipeline::CS", "structmage_1_1_pipeline_1_1_c_s.html", null ],
    [ "DDS_HEADER", "struct_d_d_s___h_e_a_d_e_r.html", null ],
    [ "DDS_HEADER_DXT10", "struct_d_d_s___h_e_a_d_e_r___d_x_t10.html", null ],
    [ "DDS_PIXELFORMAT", "struct_d_d_s___p_i_x_e_l_f_o_r_m_a_t.html", null ],
    [ "mage::DeferredShadingPass", "classmage_1_1_deferred_shading_pass.html", null ],
    [ "mage::DepthPass", "classmage_1_1_depth_pass.html", null ],
    [ "DerivedResourceT", null, [
      [ "mage::ResourcePool< KeyT, ResourceT >::Resource< DerivedResourceT >", "classmage_1_1_resource_pool_1_1_resource.html", null ]
    ] ],
    [ "mage::DirectionalLightBuffer", "structmage_1_1_directional_light_buffer.html", null ],
    [ "mage::DisplayConfiguration", "classmage_1_1_display_configuration.html", null ],
    [ "mage::DisplayConfigurator", "classmage_1_1_display_configurator.html", null ],
    [ "mage::DOFPass", "classmage_1_1_d_o_f_pass.html", null ],
    [ "mage::DoubleEndedMemoryStack", "classmage_1_1_double_ended_memory_stack.html", null ],
    [ "mage::Pipeline::DS", "structmage_1_1_pipeline_1_1_d_s.html", null ],
    [ "mage::Engine", "classmage_1_1_engine.html", null ],
    [ "mage::EngineSetup", "classmage_1_1_engine_setup.html", null ],
    [ "mage::EngineStatistics", "classmage_1_1_engine_statistics.html", null ],
    [ "exception", null, [
      [ "mage::Exception", "classmage_1_1_exception.html", null ]
    ] ],
    [ "mage::FileStreamCloser", "structmage_1_1_file_stream_closer.html", null ],
    [ "mage::Fog", "classmage_1_1_fog.html", null ],
    [ "mage::GameBuffer", "structmage_1_1_game_buffer.html", null ],
    [ "mage::GBufferPass", "classmage_1_1_g_buffer_pass.html", null ],
    [ "mage::Glyph", "structmage_1_1_glyph.html", null ],
    [ "mage::GlyphLessThan", "structmage_1_1_glyph_less_than.html", null ],
    [ "mage::Pipeline::GS", "structmage_1_1_pipeline_1_1_g_s.html", null ],
    [ "mage::HandleCloser", "structmage_1_1_handle_closer.html", null ],
    [ "mage::DoubleEndedMemoryStack::HighAllocator< DataT >", "classmage_1_1_double_ended_memory_stack_1_1_high_allocator.html", null ],
    [ "mage::Pipeline::HS", "structmage_1_1_pipeline_1_1_h_s.html", null ],
    [ "mage::Pipeline::IA", "structmage_1_1_pipeline_1_1_i_a.html", null ],
    [ "mage::IdGenerator", "classmage_1_1_id_generator.html", null ],
    [ "mage::InputManager", "classmage_1_1_input_manager.html", null ],
    [ "mage::KernelModeCoreClock", "structmage_1_1_kernel_mode_core_clock.html", null ],
    [ "mage::KernelModeCoreClockPerCore", "structmage_1_1_kernel_mode_core_clock_per_core.html", null ],
    [ "mage::Keyboard", "classmage_1_1_keyboard.html", null ],
    [ "mage::LBufferPass", "classmage_1_1_l_buffer_pass.html", null ],
    [ "mage::LightBuffer", "structmage_1_1_light_buffer.html", null ],
    [ "mage::LBufferPass::LightCameraInfo", "structmage_1_1_l_buffer_pass_1_1_light_camera_info.html", null ],
    [ "mage::LineReader", "classmage_1_1_line_reader.html", [
      [ "mage::loader::MDLReader< VertexT, IndexT >", "classmage_1_1loader_1_1_m_d_l_reader.html", null ],
      [ "mage::loader::MTLReader", "classmage_1_1loader_1_1_m_t_l_reader.html", null ],
      [ "mage::loader::OBJReader< VertexT, IndexT >", "classmage_1_1loader_1_1_o_b_j_reader.html", null ],
      [ "mage::loader::VARReader", "classmage_1_1loader_1_1_v_a_r_reader.html", null ]
    ] ],
    [ "mage::LocalTransform", "classmage_1_1_local_transform.html", null ],
    [ "mage::LoggingConfiguration", "classmage_1_1_logging_configuration.html", null ],
    [ "mage::DoubleEndedMemoryStack::LowAllocator< DataT >", "classmage_1_1_double_ended_memory_stack_1_1_low_allocator.html", null ],
    [ "mage::MainWindow", "classmage_1_1_main_window.html", null ],
    [ "mage::Material", "classmage_1_1_material.html", null ],
    [ "mage::MemoryArena", "classmage_1_1_memory_arena.html", null ],
    [ "mage::Mesh", "classmage_1_1_mesh.html", [
      [ "mage::PrimitiveBatchMesh< VertexT, IndexT >", "classmage_1_1_primitive_batch_mesh.html", null ],
      [ "mage::StaticMesh< VertexT, IndexT >", "classmage_1_1_static_mesh.html", null ],
      [ "mage::PrimitiveBatchMesh< VertexPositionColorTexture, U16 >", "classmage_1_1_primitive_batch_mesh.html", [
        [ "mage::SpriteBatchMesh", "classmage_1_1_sprite_batch_mesh.html", null ]
      ] ]
    ] ],
    [ "mage::MeshDescriptor< VertexT, IndexT >", "classmage_1_1_mesh_descriptor.html", null ],
    [ "mage::ModelBuffer", "structmage_1_1_model_buffer.html", null ],
    [ "mage::ModelNormalTextureTransformBuffer", "structmage_1_1_model_normal_texture_transform_buffer.html", null ],
    [ "mage::ModelNormalTransformBuffer", "structmage_1_1_model_normal_transform_buffer.html", null ],
    [ "mage::ModelOutput< VertexT, IndexT >", "structmage_1_1_model_output.html", null ],
    [ "mage::ModelPart", "structmage_1_1_model_part.html", null ],
    [ "mage::ModelTextureTransformBuffer", "structmage_1_1_model_texture_transform_buffer.html", null ],
    [ "mage::Mouse", "classmage_1_1_mouse.html", null ],
    [ "mage::Node", "classmage_1_1_node.html", null ],
    [ "mage::NodeClient", "classmage_1_1_node_client.html", null ],
    [ "mage::loader::OBJReader< VertexT, IndexT >::OBJComparatorIndex3", "structmage_1_1loader_1_1_o_b_j_reader_1_1_o_b_j_comparator_index3.html", null ],
    [ "mage::Pipeline::OM", "structmage_1_1_pipeline_1_1_o_m.html", null ],
    [ "mage::OmniLightBuffer", "structmage_1_1_omni_light_buffer.html", null ],
    [ "mage::PersistentResourcePool< KeyT, ResourceT >", "classmage_1_1_persistent_resource_pool.html", null ],
    [ "mage::Pipeline", "structmage_1_1_pipeline.html", null ],
    [ "mage::ProgressReporter", "classmage_1_1_progress_reporter.html", null ],
    [ "mage::ProxyPtr< T >", "classmage_1_1_proxy_ptr.html", null ],
    [ "mage::ProxyPtr< mage::Node >", "classmage_1_1_proxy_ptr.html", null ],
    [ "mage::ProxyPtr< mage::SpriteText >", "classmage_1_1_proxy_ptr.html", null ],
    [ "mage::ProxyPtr< Node >", "classmage_1_1_proxy_ptr.html", null ],
    [ "mage::Pipeline::PS", "structmage_1_1_pipeline_1_1_p_s.html", null ],
    [ "mage::AlignedAllocator< DataT, AlignmentS >::rebind< DataU >", "structmage_1_1_aligned_allocator_1_1rebind.html", null ],
    [ "mage::Renderer", "classmage_1_1_renderer.html", null ],
    [ "mage::RenderingManager", "classmage_1_1_rendering_manager.html", null ],
    [ "mage::RenderingOutputManager", "classmage_1_1_rendering_output_manager.html", null ],
    [ "mage::RenderingStateManager", "classmage_1_1_rendering_state_manager.html", null ],
    [ "mage::Resource< ResourceT >", "classmage_1_1_resource.html", null ],
    [ "mage::Resource< ModelDescriptor >", "classmage_1_1_resource.html", [
      [ "mage::ModelDescriptor", "classmage_1_1_model_descriptor.html", null ]
    ] ],
    [ "mage::Resource< Shader< ShaderT, PipelineStageT > >", "classmage_1_1_resource.html", [
      [ "mage::Shader< ShaderT, PipelineStageT >", "classmage_1_1_shader.html", null ]
    ] ],
    [ "mage::Resource< SpriteFont >", "classmage_1_1_resource.html", [
      [ "mage::SpriteFont", "classmage_1_1_sprite_font.html", null ]
    ] ],
    [ "mage::Resource< Texture >", "classmage_1_1_resource.html", [
      [ "mage::Texture", "classmage_1_1_texture.html", null ]
    ] ],
    [ "mage::Resource< VariableScript >", "classmage_1_1_resource.html", [
      [ "mage::VariableScript", "classmage_1_1_variable_script.html", null ]
    ] ],
    [ "mage::Resource< VertexShader >", "classmage_1_1_resource.html", [
      [ "mage::VertexShader", "classmage_1_1_vertex_shader.html", null ]
    ] ],
    [ "mage::ResourceManager", "classmage_1_1_resource_manager.html", null ],
    [ "mage::ResourcePool< KeyT, ResourceT >", "classmage_1_1_resource_pool.html", null ],
    [ "mage::ResourceManager::ResourceRecord< ResourceT >", "structmage_1_1_resource_manager_1_1_resource_record.html", null ],
    [ "mage::ResourceManager::ResourceRecord< ComputeShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_compute_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< DomainShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_domain_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< GeometryShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_geometry_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< HullShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_hull_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< PixelShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_pixel_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< VariableScript >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_variable_script_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< VertexShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_vertex_shader_01_4.html", null ],
    [ "mage::RNG", "classmage_1_1_r_n_g.html", null ],
    [ "mage::Pipeline::RS", "structmage_1_1_pipeline_1_1_r_s.html", null ],
    [ "mage::Scene", "classmage_1_1_scene.html", null ],
    [ "mage::SceneManager", "classmage_1_1_scene_manager.html", null ],
    [ "mage::ShadingNormalPass", "classmage_1_1_shading_normal_pass.html", null ],
    [ "mage::ShadowCubeMapBuffer", "structmage_1_1_shadow_cube_map_buffer.html", null ],
    [ "mage::ShadowMapBuffer", "structmage_1_1_shadow_map_buffer.html", null ],
    [ "mage::ShadowMappedDirectionalLightBuffer", "structmage_1_1_shadow_mapped_directional_light_buffer.html", null ],
    [ "mage::ShadowMappedOmniLightBuffer", "structmage_1_1_shadow_mapped_omni_light_buffer.html", null ],
    [ "mage::ShadowMappedSpotLightBuffer", "structmage_1_1_shadow_mapped_spot_light_buffer.html", null ],
    [ "mage::SingleEndedMemoryStack", "classmage_1_1_single_ended_memory_stack.html", null ],
    [ "mage::Sky", "classmage_1_1_sky.html", null ],
    [ "mage::SkyPass", "classmage_1_1_sky_pass.html", null ],
    [ "mage::Pipeline::SO", "structmage_1_1_pipeline_1_1_s_o.html", null ],
    [ "mage::SpotLightBuffer", "structmage_1_1_spot_light_buffer.html", null ],
    [ "mage::SpriteBatch", "classmage_1_1_sprite_batch.html", null ],
    [ "mage::SpriteFontDescriptor", "classmage_1_1_sprite_font_descriptor.html", null ],
    [ "mage::SpriteFontOutput", "structmage_1_1_sprite_font_output.html", null ],
    [ "mage::SpriteInfo", "structmage_1_1_sprite_info.html", null ],
    [ "mage::SpritePass", "classmage_1_1_sprite_pass.html", null ],
    [ "mage::SpriteTransform", "classmage_1_1_sprite_transform.html", null ],
    [ "mage::StructuredBuffer< DataT >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::DirectionalLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::OmniLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::ShadowMappedDirectionalLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::ShadowMappedOmniLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::ShadowMappedSpotLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::SpotLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::SwapChain", "classmage_1_1_swap_chain.html", null ],
    [ "mage::SystemClock", "structmage_1_1_system_clock.html", null ],
    [ "mage::TextureTransform", "classmage_1_1_texture_transform.html", null ],
    [ "mage::Timer< ClockT >", "classmage_1_1_timer.html", null ],
    [ "mage::Timer< CoreClockPerCore >", "classmage_1_1_timer.html", null ],
    [ "mage::Timer< std::chrono::high_resolution_clock >", "classmage_1_1_timer.html", null ],
    [ "mage::Transform", "classmage_1_1_transform.html", null ],
    [ "mage::TransformClient", "classmage_1_1_transform_client.html", null ],
    [ "mage::Pipeline::TS", "structmage_1_1_pipeline_1_1_t_s.html", null ],
    [ "mage::UserModeCoreClock", "structmage_1_1_user_mode_core_clock.html", null ],
    [ "mage::UserModeCoreClockPerCore", "structmage_1_1_user_mode_core_clock_per_core.html", null ],
    [ "mage::VariableComponentPass", "classmage_1_1_variable_component_pass.html", null ],
    [ "mage::VariableShadingPass", "classmage_1_1_variable_shading_pass.html", null ],
    [ "mage::Vector2< T, Enable >", "structmage_1_1_vector2.html", [
      [ "mage::UV", "structmage_1_1_u_v.html", null ]
    ] ],
    [ "mage::Vector2< F32 >", "structmage_1_1_vector2.html", null ],
    [ "mage::Vector2< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector2_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__v_3_01_t_01_4_00_01void_01_4_01_4.html", null ],
    [ "mage::Vector2A< T, Enable >", "structmage_1_1_vector2_a.html", null ],
    [ "mage::Vector2A< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector2_a_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__b421e7a25afc1ac5972d3b452777021a.html", null ],
    [ "mage::Vector3< T, Enable >", "structmage_1_1_vector3.html", [
      [ "mage::Direction3", "structmage_1_1_direction3.html", null ],
      [ "mage::Point3", "structmage_1_1_point3.html", null ],
      [ "mage::RGB", "structmage_1_1_r_g_b.html", null ]
    ] ],
    [ "mage::Vector3< F32 >", "structmage_1_1_vector3.html", [
      [ "mage::Normal3", "structmage_1_1_normal3.html", null ],
      [ "mage::SRGB", "structmage_1_1_s_r_g_b.html", null ],
      [ "mage::XYZ", "structmage_1_1_x_y_z.html", null ]
    ] ],
    [ "mage::Vector3< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector3_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__v_3_01_t_01_4_00_01void_01_4_01_4.html", null ],
    [ "mage::Vector3A< T, Enable >", "structmage_1_1_vector3_a.html", null ],
    [ "mage::Vector3A< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector3_a_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__7070ab83646a86866d1e3c9d7eeea37a.html", null ],
    [ "mage::Vector4< T, Enable >", "structmage_1_1_vector4.html", [
      [ "mage::RGBA", "structmage_1_1_r_g_b_a.html", null ],
      [ "mage::SRGBA", "structmage_1_1_s_r_g_b_a.html", null ],
      [ "mage::XYZA", "structmage_1_1_x_y_z_a.html", null ]
    ] ],
    [ "mage::Vector4< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector4_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__v_3_01_t_01_4_00_01void_01_4_01_4.html", null ],
    [ "mage::Vector4A< T, Enable >", "structmage_1_1_vector4_a.html", null ],
    [ "mage::Vector4A< F32 >", "structmage_1_1_vector4_a.html", null ],
    [ "mage::Vector4A< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector4_a_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__d13db15ba42d9bdb5e20df00543b38a7.html", null ],
    [ "mage::VertexPosition", "structmage_1_1_vertex_position.html", null ],
    [ "mage::VertexPositionColor", "structmage_1_1_vertex_position_color.html", null ],
    [ "mage::VertexPositionColorTexture", "structmage_1_1_vertex_position_color_texture.html", null ],
    [ "mage::VertexPositionNormal", "structmage_1_1_vertex_position_normal.html", null ],
    [ "mage::VertexPositionNormalColor", "structmage_1_1_vertex_position_normal_color.html", null ],
    [ "mage::VertexPositionNormalColorTexture", "structmage_1_1_vertex_position_normal_color_texture.html", null ],
    [ "mage::VertexPositionNormalTexture", "structmage_1_1_vertex_position_normal_texture.html", null ],
    [ "mage::VertexPositionTexture", "structmage_1_1_vertex_position_texture.html", null ],
    [ "mage::Viewport", "classmage_1_1_viewport.html", null ],
    [ "mage::VoxelGrid", "classmage_1_1_voxel_grid.html", null ],
    [ "mage::VoxelizationPass", "classmage_1_1_voxelization_pass.html", null ],
    [ "mage::Pipeline::VS", "structmage_1_1_pipeline_1_1_v_s.html", null ],
    [ "mage::WireframePass", "classmage_1_1_wireframe_pass.html", null ],
    [ "mage::Writer", "classmage_1_1_writer.html", [
      [ "mage::loader::MDLWriter< VertexT, IndexT >", "classmage_1_1loader_1_1_m_d_l_writer.html", null ],
      [ "mage::loader::VARWriter", "classmage_1_1loader_1_1_v_a_r_writer.html", null ]
    ] ]
];