var hierarchy =
[
    [ "mage::AABB", "classmage_1_1_a_a_b_b.html", null ],
    [ "mage::AAPass", "classmage_1_1_a_a_pass.html", null ],
    [ "mage::AlignedAllocator< DataT, AlignmentS >", "classmage_1_1_aligned_allocator.html", null ],
    [ "mage::SingleEndedMemoryStack::Allocator< DataT >", "classmage_1_1_single_ended_memory_stack_1_1_allocator.html", null ],
    [ "mage::MemoryArena::Allocator< DataT >", "classmage_1_1_memory_arena_1_1_allocator.html", null ],
    [ "mage::BackBufferPass", "classmage_1_1_back_buffer_pass.html", null ],
    [ "mage::BigEndianBinaryReader", "classmage_1_1_big_endian_binary_reader.html", [
      [ "mage::loader::MSHReader< VertexT, IndexT >", "classmage_1_1loader_1_1_m_s_h_reader.html", null ],
      [ "mage::loader::SpriteFontReader", "classmage_1_1loader_1_1_sprite_font_reader.html", null ]
    ] ],
    [ "mage::BigEndianBinaryWriter", "classmage_1_1_big_endian_binary_writer.html", [
      [ "mage::loader::MSHWriter< VertexT, IndexT >", "classmage_1_1loader_1_1_m_s_h_writer.html", null ]
    ] ],
    [ "mage::BinaryReader", "classmage_1_1_binary_reader.html", null ],
    [ "mage::BoundingFrustum", "classmage_1_1_bounding_frustum.html", null ],
    [ "mage::BoundingSphere", "classmage_1_1_bounding_sphere.html", null ],
    [ "mage::BoundingVolumePass", "classmage_1_1_bounding_volume_pass.html", null ],
    [ "mage::BufferLock", "classmage_1_1_buffer_lock.html", null ],
    [ "mage::CameraBuffer", "structmage_1_1_camera_buffer.html", null ],
    [ "mage::CameraLens", "classmage_1_1_camera_lens.html", null ],
    [ "mage::CameraSettings", "classmage_1_1_camera_settings.html", null ],
    [ "mage::ColorString", "classmage_1_1_color_string.html", null ],
    [ "mage::CompiledShader", "classmage_1_1_compiled_shader.html", [
      [ "mage::BlobCompiledShader", "classmage_1_1_blob_compiled_shader.html", null ],
      [ "mage::BufferCompiledShader", "classmage_1_1_buffer_compiled_shader.html", null ]
    ] ],
    [ "mage::Component", "classmage_1_1_component.html", [
      [ "mage::AmbientLight", "classmage_1_1_ambient_light.html", null ],
      [ "mage::BehaviorScript", "classmage_1_1_behavior_script.html", [
        [ "mage::script::CharacterMotorScript", "classmage_1_1script_1_1_character_motor_script.html", null ],
        [ "mage::script::EditorScript", "classmage_1_1script_1_1_editor_script.html", null ],
        [ "mage::script::ManhattanMotorScript", "classmage_1_1script_1_1_manhattan_motor_script.html", null ],
        [ "mage::script::MouseLookScript", "classmage_1_1script_1_1_mouse_look_script.html", null ],
        [ "mage::script::RotationScript", "classmage_1_1script_1_1_rotation_script.html", null ],
        [ "mage::script::StatsScript", "classmage_1_1script_1_1_stats_script.html", null ],
        [ "mage::script::SwitchSceneScript< SceneT >", "classmage_1_1script_1_1_switch_scene_script.html", null ],
        [ "mage::script::TextConsoleScript", "classmage_1_1script_1_1_text_console_script.html", null ]
      ] ],
      [ "mage::Camera", "classmage_1_1_camera.html", [
        [ "mage::OrthographicCamera", "classmage_1_1_orthographic_camera.html", null ],
        [ "mage::PerspectiveCamera", "classmage_1_1_perspective_camera.html", null ]
      ] ],
      [ "mage::DirectionalLight", "classmage_1_1_directional_light.html", null ],
      [ "mage::Model", "classmage_1_1_model.html", null ],
      [ "mage::OmniLight", "classmage_1_1_omni_light.html", null ],
      [ "mage::SpotLight", "classmage_1_1_spot_light.html", null ],
      [ "mage::SpriteImage", "classmage_1_1_sprite_image.html", null ],
      [ "mage::SpriteText", "classmage_1_1_sprite_text.html", null ]
    ] ],
    [ "mage::ComponentClient", "classmage_1_1_component_client.html", null ],
    [ "mage::ConstantBuffer< DataT >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::CameraBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::GameBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::LightBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::ModelBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::ModelNormalTextureTransformBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::ModelNormalTransformBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::ModelTextureTransformBuffer >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< mage::RGBA >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< XMMATRIX >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantBuffer< XMVECTOR >", "classmage_1_1_constant_buffer.html", null ],
    [ "mage::ConstantComponentPass", "classmage_1_1_constant_component_pass.html", null ],
    [ "mage::ConstantShadingPass", "classmage_1_1_constant_shading_pass.html", null ],
    [ "mage::CPUMonitor", "classmage_1_1_c_p_u_monitor.html", null ],
    [ "mage::CPUTimer", "classmage_1_1_c_p_u_timer.html", null ],
    [ "mage::Pipeline::CS", "structmage_1_1_pipeline_1_1_c_s.html", null ],
    [ "ImFontAtlas::CustomRect", "struct_im_font_atlas_1_1_custom_rect.html", null ],
    [ "DDS_HEADER", "struct_d_d_s___h_e_a_d_e_r.html", null ],
    [ "DDS_HEADER_DXT10", "struct_d_d_s___h_e_a_d_e_r___d_x_t10.html", null ],
    [ "DDS_PIXELFORMAT", "struct_d_d_s___p_i_x_e_l_f_o_r_m_a_t.html", null ],
    [ "mage::DeferredShadingPass", "classmage_1_1_deferred_shading_pass.html", null ],
    [ "mage::DepthPass", "classmage_1_1_depth_pass.html", null ],
    [ "DerivedResourceT", null, [
      [ "mage::ResourcePool< KeyT, ResourceT >::Resource< DerivedResourceT >", "classmage_1_1_resource_pool_1_1_resource.html", null ]
    ] ],
    [ "mage::DirectionalLightBuffer", "structmage_1_1_directional_light_buffer.html", null ],
    [ "mage::DirectionalLightWithShadowMappingBuffer", "structmage_1_1_directional_light_with_shadow_mapping_buffer.html", null ],
    [ "mage::DisplayConfiguration", "classmage_1_1_display_configuration.html", null ],
    [ "mage::DisplayConfigurator", "classmage_1_1_display_configurator.html", null ],
    [ "mage::DOFPass", "classmage_1_1_d_o_f_pass.html", null ],
    [ "mage::DoubleEndedMemoryStack", "classmage_1_1_double_ended_memory_stack.html", null ],
    [ "mage::Pipeline::DS", "structmage_1_1_pipeline_1_1_d_s.html", null ],
    [ "mage::Engine", "classmage_1_1_engine.html", null ],
    [ "mage::EngineSetup", "classmage_1_1_engine_setup.html", null ],
    [ "mage::EngineStatistics", "classmage_1_1_engine_statistics.html", null ],
    [ "ExampleAppConsole", "struct_example_app_console.html", null ],
    [ "ExampleAppLog", "struct_example_app_log.html", null ],
    [ "exception", null, [
      [ "mage::Exception", "classmage_1_1_exception.html", null ]
    ] ],
    [ "mage::FileStreamCloser", "structmage_1_1_file_stream_closer.html", null ],
    [ "mage::Fog", "classmage_1_1_fog.html", null ],
    [ "mage::GameBuffer", "structmage_1_1_game_buffer.html", null ],
    [ "mage::GBufferPass", "classmage_1_1_g_buffer_pass.html", null ],
    [ "mage::Glyph", "structmage_1_1_glyph.html", null ],
    [ "mage::GlyphLessThan", "structmage_1_1_glyph_less_than.html", null ],
    [ "ImFontAtlas::GlyphRangesBuilder", "struct_im_font_atlas_1_1_glyph_ranges_builder.html", null ],
    [ "mage::Pipeline::GS", "structmage_1_1_pipeline_1_1_g_s.html", null ],
    [ "mage::HandleCloser", "structmage_1_1_handle_closer.html", null ],
    [ "mage::DoubleEndedMemoryStack::HighAllocator< DataT >", "classmage_1_1_double_ended_memory_stack_1_1_high_allocator.html", null ],
    [ "mage::Pipeline::HS", "structmage_1_1_pipeline_1_1_h_s.html", null ],
    [ "mage::Pipeline::IA", "structmage_1_1_pipeline_1_1_i_a.html", null ],
    [ "mage::IdGenerator", "classmage_1_1_id_generator.html", null ],
    [ "ImColor", "struct_im_color.html", null ],
    [ "ImDrawChannel", "struct_im_draw_channel.html", null ],
    [ "ImDrawCmd", "struct_im_draw_cmd.html", null ],
    [ "ImDrawData", "struct_im_draw_data.html", null ],
    [ "ImDrawList", "struct_im_draw_list.html", null ],
    [ "ImDrawListSharedData", "struct_im_draw_list_shared_data.html", null ],
    [ "ImDrawVert", "struct_im_draw_vert.html", null ],
    [ "ImFont", "struct_im_font.html", null ],
    [ "ImFontAtlas", "struct_im_font_atlas.html", null ],
    [ "ImFontConfig", "struct_im_font_config.html", null ],
    [ "ImFontGlyph", "struct_im_font_glyph.html", null ],
    [ "ImGuiColMod", "struct_im_gui_col_mod.html", null ],
    [ "ImGuiColumnData", "struct_im_gui_column_data.html", null ],
    [ "ImGuiColumnsSet", "struct_im_gui_columns_set.html", null ],
    [ "ImGuiContext", "struct_im_gui_context.html", null ],
    [ "ImGuiDrawContext", "struct_im_gui_draw_context.html", null ],
    [ "ImGuiGroupData", "struct_im_gui_group_data.html", null ],
    [ "ImGuiIO", "struct_im_gui_i_o.html", null ],
    [ "ImGuiItemHoveredDataBackup", "struct_im_gui_item_hovered_data_backup.html", null ],
    [ "ImGuiListClipper", "struct_im_gui_list_clipper.html", null ],
    [ "ImGuiMouseCursorData", "struct_im_gui_mouse_cursor_data.html", null ],
    [ "ImGuiOnceUponAFrame", "struct_im_gui_once_upon_a_frame.html", null ],
    [ "ImGuiPayload", "struct_im_gui_payload.html", null ],
    [ "ImGuiPlotArrayGetterData", "struct_im_gui_plot_array_getter_data.html", null ],
    [ "ImGuiPopupRef", "struct_im_gui_popup_ref.html", null ],
    [ "ImGuiResizeGripDef", "struct_im_gui_resize_grip_def.html", null ],
    [ "ImGuiSettingsHandler", "struct_im_gui_settings_handler.html", null ],
    [ "ImGuiSimpleColumns", "struct_im_gui_simple_columns.html", null ],
    [ "ImGuiSizeConstraintCallbackData", "struct_im_gui_size_constraint_callback_data.html", null ],
    [ "ImGuiStorage", "struct_im_gui_storage.html", null ],
    [ "ImGuiStyle", "struct_im_gui_style.html", null ],
    [ "ImGuiStyleMod", "struct_im_gui_style_mod.html", null ],
    [ "ImGuiStyleVarInfo", "struct_im_gui_style_var_info.html", null ],
    [ "ImGuiTextBuffer", "struct_im_gui_text_buffer.html", null ],
    [ "ImGuiTextEditCallbackData", "struct_im_gui_text_edit_callback_data.html", null ],
    [ "ImGuiTextEditState", "struct_im_gui_text_edit_state.html", null ],
    [ "ImGuiTextFilter", "struct_im_gui_text_filter.html", null ],
    [ "ImGuiWindow", "struct_im_gui_window.html", null ],
    [ "ImGuiWindowSettings", "struct_im_gui_window_settings.html", null ],
    [ "ImPlacementNewDummy", "struct_im_placement_new_dummy.html", null ],
    [ "ImRect", "struct_im_rect.html", null ],
    [ "ImVec2", "struct_im_vec2.html", null ],
    [ "ImVec4", "struct_im_vec4.html", null ],
    [ "ImVector< T >", "class_im_vector.html", null ],
    [ "ImVector< char *>", "class_im_vector.html", null ],
    [ "ImVector< char >", "class_im_vector.html", null ],
    [ "ImVector< const char *>", "class_im_vector.html", null ],
    [ "ImVector< float >", "class_im_vector.html", null ],
    [ "ImVector< ImDrawChannel >", "class_im_vector.html", null ],
    [ "ImVector< ImDrawCmd >", "class_im_vector.html", null ],
    [ "ImVector< ImDrawIdx >", "class_im_vector.html", null ],
    [ "ImVector< ImDrawList *>", "class_im_vector.html", null ],
    [ "ImVector< ImDrawVert >", "class_im_vector.html", null ],
    [ "ImVector< ImFont *>", "class_im_vector.html", null ],
    [ "ImVector< ImFontAtlas::CustomRect >", "class_im_vector.html", null ],
    [ "ImVector< ImFontConfig >", "class_im_vector.html", null ],
    [ "ImVector< ImFontGlyph >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiColMod >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiColumnData >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiColumnsSet >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiGroupData >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiID >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiItemFlags >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiPopupRef >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiSettingsHandler >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiStorage::Pair >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiStyleMod >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiTextFilter::TextRange >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiWindow *>", "class_im_vector.html", null ],
    [ "ImVector< ImGuiWindowSettings >", "class_im_vector.html", null ],
    [ "ImVector< ImTextureID >", "class_im_vector.html", null ],
    [ "ImVector< ImVec2 >", "class_im_vector.html", null ],
    [ "ImVector< ImVec4 >", "class_im_vector.html", null ],
    [ "ImVector< ImWchar >", "class_im_vector.html", null ],
    [ "ImVector< int >", "class_im_vector.html", null ],
    [ "ImVector< unsigned char >", "class_im_vector.html", null ],
    [ "ImVector< unsigned short >", "class_im_vector.html", null ],
    [ "mage::InputManager", "classmage_1_1_input_manager.html", null ],
    [ "mage::Keyboard", "classmage_1_1_keyboard.html", null ],
    [ "mage::LBufferPass", "structmage_1_1_l_buffer_pass.html", null ],
    [ "mage::LightBuffer", "structmage_1_1_light_buffer.html", null ],
    [ "mage::LightCameraInfo", "structmage_1_1_light_camera_info.html", null ],
    [ "mage::LineReader", "classmage_1_1_line_reader.html", [
      [ "mage::loader::MDLReader< VertexT, IndexT >", "classmage_1_1loader_1_1_m_d_l_reader.html", null ],
      [ "mage::loader::MTLReader", "classmage_1_1loader_1_1_m_t_l_reader.html", null ],
      [ "mage::loader::OBJReader< VertexT, IndexT >", "classmage_1_1loader_1_1_o_b_j_reader.html", null ],
      [ "mage::loader::VARReader", "classmage_1_1loader_1_1_v_a_r_reader.html", null ]
    ] ],
    [ "mage::LocalTransform", "classmage_1_1_local_transform.html", null ],
    [ "mage::LoggingConfiguration", "classmage_1_1_logging_configuration.html", null ],
    [ "mage::DoubleEndedMemoryStack::LowAllocator< DataT >", "classmage_1_1_double_ended_memory_stack_1_1_low_allocator.html", null ],
    [ "mage::MainWindow", "classmage_1_1_main_window.html", null ],
    [ "mage::Material", "classmage_1_1_material.html", null ],
    [ "mage::MemoryArena", "classmage_1_1_memory_arena.html", null ],
    [ "mage::Mesh", "classmage_1_1_mesh.html", [
      [ "mage::PrimitiveBatchMesh< VertexT, IndexT >", "classmage_1_1_primitive_batch_mesh.html", null ],
      [ "mage::StaticMesh< VertexT, IndexT >", "classmage_1_1_static_mesh.html", null ],
      [ "mage::PrimitiveBatchMesh< VertexPositionColorTexture, U16 >", "classmage_1_1_primitive_batch_mesh.html", [
        [ "mage::SpriteBatchMesh", "classmage_1_1_sprite_batch_mesh.html", null ]
      ] ]
    ] ],
    [ "mage::MeshDescriptor< VertexT, IndexT >", "classmage_1_1_mesh_descriptor.html", null ],
    [ "mage::ModelBuffer", "structmage_1_1_model_buffer.html", null ],
    [ "mage::ModelNormalTextureTransformBuffer", "structmage_1_1_model_normal_texture_transform_buffer.html", null ],
    [ "mage::ModelNormalTransformBuffer", "structmage_1_1_model_normal_transform_buffer.html", null ],
    [ "mage::ModelOutput< VertexT, IndexT >", "structmage_1_1_model_output.html", null ],
    [ "mage::ModelPart", "structmage_1_1_model_part.html", null ],
    [ "mage::ModelTextureTransformBuffer", "structmage_1_1_model_texture_transform_buffer.html", null ],
    [ "mage::Mouse", "classmage_1_1_mouse.html", null ],
    [ "mage::Node", "classmage_1_1_node.html", null ],
    [ "mage::NodeClient", "classmage_1_1_node_client.html", null ],
    [ "mage::loader::OBJReader< VertexT, IndexT >::OBJComparatorIndex3", "structmage_1_1loader_1_1_o_b_j_reader_1_1_o_b_j_comparator_index3.html", null ],
    [ "mage::Pipeline::OM", "structmage_1_1_pipeline_1_1_o_m.html", null ],
    [ "mage::OmniLightBuffer", "structmage_1_1_omni_light_buffer.html", null ],
    [ "mage::OmniLightWithShadowMappingBuffer", "structmage_1_1_omni_light_with_shadow_mapping_buffer.html", null ],
    [ "ImGuiStorage::Pair", "struct_im_gui_storage_1_1_pair.html", null ],
    [ "mage::PersistentResourcePool< KeyT, ResourceT >", "classmage_1_1_persistent_resource_pool.html", null ],
    [ "mage::Pipeline", "structmage_1_1_pipeline.html", null ],
    [ "mage::ProgressReporter", "classmage_1_1_progress_reporter.html", null ],
    [ "mage::ProxyPtr< T >", "classmage_1_1_proxy_ptr.html", null ],
    [ "mage::ProxyPtr< mage::Node >", "classmage_1_1_proxy_ptr.html", null ],
    [ "mage::ProxyPtr< mage::SpriteText >", "classmage_1_1_proxy_ptr.html", null ],
    [ "mage::ProxyPtr< Node >", "classmage_1_1_proxy_ptr.html", null ],
    [ "mage::Pipeline::PS", "structmage_1_1_pipeline_1_1_p_s.html", null ],
    [ "mage::AlignedAllocator< DataT, AlignmentS >::rebind< DataU >", "structmage_1_1_aligned_allocator_1_1rebind.html", null ],
    [ "mage::Renderer", "classmage_1_1_renderer.html", null ],
    [ "mage::RenderingManager", "classmage_1_1_rendering_manager.html", null ],
    [ "mage::RenderingOutputManager", "classmage_1_1_rendering_output_manager.html", null ],
    [ "mage::RenderingStateManager", "classmage_1_1_rendering_state_manager.html", null ],
    [ "mage::Resource< ResourceT >", "classmage_1_1_resource.html", null ],
    [ "mage::Resource< ModelDescriptor >", "classmage_1_1_resource.html", [
      [ "mage::ModelDescriptor", "classmage_1_1_model_descriptor.html", null ]
    ] ],
    [ "mage::Resource< Shader< ShaderT, PipelineStageT > >", "classmage_1_1_resource.html", [
      [ "mage::Shader< ShaderT, PipelineStageT >", "classmage_1_1_shader.html", null ]
    ] ],
    [ "mage::Resource< SpriteFont >", "classmage_1_1_resource.html", [
      [ "mage::SpriteFont", "classmage_1_1_sprite_font.html", null ]
    ] ],
    [ "mage::Resource< Texture >", "classmage_1_1_resource.html", [
      [ "mage::Texture", "classmage_1_1_texture.html", null ]
    ] ],
    [ "mage::Resource< VariableScript >", "classmage_1_1_resource.html", [
      [ "mage::VariableScript", "classmage_1_1_variable_script.html", null ]
    ] ],
    [ "mage::Resource< VertexShader >", "classmage_1_1_resource.html", [
      [ "mage::VertexShader", "classmage_1_1_vertex_shader.html", null ]
    ] ],
    [ "mage::ResourceManager", "classmage_1_1_resource_manager.html", null ],
    [ "mage::ResourcePool< KeyT, ResourceT >", "classmage_1_1_resource_pool.html", null ],
    [ "mage::ResourceManager::ResourceRecord< ResourceT >", "structmage_1_1_resource_manager_1_1_resource_record.html", null ],
    [ "mage::ResourceManager::ResourceRecord< ComputeShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_compute_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< DomainShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_domain_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< GeometryShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_geometry_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< HullShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_hull_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< PixelShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_pixel_shader_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< VariableScript >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_variable_script_01_4.html", null ],
    [ "mage::ResourceManager::ResourceRecord< VertexShader >", "structmage_1_1_resource_manager_1_1_resource_record_3_01_vertex_shader_01_4.html", null ],
    [ "mage::RNG", "classmage_1_1_r_n_g.html", null ],
    [ "mage::Pipeline::RS", "structmage_1_1_pipeline_1_1_r_s.html", null ],
    [ "mage::Scene", "classmage_1_1_scene.html", null ],
    [ "mage::SceneManager", "classmage_1_1_scene_manager.html", null ],
    [ "mage::ShadingNormalPass", "classmage_1_1_shading_normal_pass.html", null ],
    [ "mage::ShadowCubeMapBuffer", "structmage_1_1_shadow_cube_map_buffer.html", null ],
    [ "mage::ShadowMapBuffer", "structmage_1_1_shadow_map_buffer.html", null ],
    [ "mage::SingleEndedMemoryStack", "classmage_1_1_single_ended_memory_stack.html", null ],
    [ "mage::Sky", "classmage_1_1_sky.html", null ],
    [ "mage::SkyPass", "classmage_1_1_sky_pass.html", null ],
    [ "mage::Pipeline::SO", "structmage_1_1_pipeline_1_1_s_o.html", null ],
    [ "mage::SpotLightBuffer", "structmage_1_1_spot_light_buffer.html", null ],
    [ "mage::SpotLightWithShadowMappingBuffer", "structmage_1_1_spot_light_with_shadow_mapping_buffer.html", null ],
    [ "mage::SpriteBatch", "classmage_1_1_sprite_batch.html", null ],
    [ "mage::SpriteFontDescriptor", "classmage_1_1_sprite_font_descriptor.html", null ],
    [ "mage::SpriteFontOutput", "structmage_1_1_sprite_font_output.html", null ],
    [ "mage::SpriteInfo", "structmage_1_1_sprite_info.html", null ],
    [ "mage::SpritePass", "classmage_1_1_sprite_pass.html", null ],
    [ "mage::SpriteTransform", "classmage_1_1_sprite_transform.html", null ],
    [ "STB_TexteditState", "struct_s_t_b___textedit_state.html", null ],
    [ "stbrp_context", "structstbrp__context.html", null ],
    [ "stbrp_node", "structstbrp__node.html", null ],
    [ "stbrp_rect", "structstbrp__rect.html", null ],
    [ "StbTexteditRow", "struct_stb_textedit_row.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "StbUndoRecord", "struct_stb_undo_record.html", null ],
    [ "StbUndoState", "struct_stb_undo_state.html", null ],
    [ "mage::StructuredBuffer< DataT >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::DirectionalLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::DirectionalLightWithShadowMappingBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::OmniLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::OmniLightWithShadowMappingBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::SpotLightBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::StructuredBuffer< mage::SpotLightWithShadowMappingBuffer >", "classmage_1_1_structured_buffer.html", null ],
    [ "mage::SwapChain", "classmage_1_1_swap_chain.html", null ],
    [ "ImGuiTextFilter::TextRange", "struct_im_gui_text_filter_1_1_text_range.html", null ],
    [ "mage::TextureTransform", "classmage_1_1_texture_transform.html", null ],
    [ "mage::Timer", "classmage_1_1_timer.html", null ],
    [ "mage::Transform", "classmage_1_1_transform.html", null ],
    [ "mage::TransformClient", "classmage_1_1_transform_client.html", null ],
    [ "mage::Pipeline::TS", "structmage_1_1_pipeline_1_1_t_s.html", null ],
    [ "mage::VariableComponentPass", "classmage_1_1_variable_component_pass.html", null ],
    [ "mage::VariableShadingPass", "classmage_1_1_variable_shading_pass.html", null ],
    [ "mage::Vector2< T, Enable >", "structmage_1_1_vector2.html", null ],
    [ "mage::Vector2< F32 >", "structmage_1_1_vector2.html", [
      [ "mage::UV", "structmage_1_1_u_v.html", null ]
    ] ],
    [ "mage::Vector2< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector2_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__v_3_01_t_01_4_00_01void_01_4_01_4.html", null ],
    [ "mage::Vector2A< T, Enable >", "structmage_1_1_vector2_a.html", null ],
    [ "mage::Vector2A< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector2_a_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__b421e7a25afc1ac5972d3b452777021a.html", null ],
    [ "mage::Vector3< T, Enable >", "structmage_1_1_vector3.html", [
      [ "mage::Direction3", "structmage_1_1_direction3.html", null ],
      [ "mage::Point3", "structmage_1_1_point3.html", null ],
      [ "mage::RGB", "structmage_1_1_r_g_b.html", null ]
    ] ],
    [ "mage::Vector3< F32 >", "structmage_1_1_vector3.html", [
      [ "mage::Normal3", "structmage_1_1_normal3.html", null ],
      [ "mage::SRGB", "structmage_1_1_s_r_g_b.html", null ],
      [ "mage::XYZ", "structmage_1_1_x_y_z.html", null ]
    ] ],
    [ "mage::Vector3< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector3_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__v_3_01_t_01_4_00_01void_01_4_01_4.html", null ],
    [ "mage::Vector3A< T, Enable >", "structmage_1_1_vector3_a.html", null ],
    [ "mage::Vector3A< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector3_a_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__7070ab83646a86866d1e3c9d7eeea37a.html", null ],
    [ "mage::Vector4< T, Enable >", "structmage_1_1_vector4.html", [
      [ "mage::RGBA", "structmage_1_1_r_g_b_a.html", null ],
      [ "mage::SRGBA", "structmage_1_1_s_r_g_b_a.html", null ],
      [ "mage::XYZA", "structmage_1_1_x_y_z_a.html", null ]
    ] ],
    [ "mage::Vector4< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector4_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__v_3_01_t_01_4_00_01void_01_4_01_4.html", null ],
    [ "mage::Vector4A< T, Enable >", "structmage_1_1_vector4_a.html", null ],
    [ "mage::Vector4A< F32 >", "structmage_1_1_vector4_a.html", null ],
    [ "mage::Vector4A< T, typename std::enable_if_t< std::is_arithmetic_v< T >, void > >", "structmage_1_1_vector4_a_3_01_t_00_01typename_01std_1_1enable__if__t_3_01std_1_1is__arithmetic__d13db15ba42d9bdb5e20df00543b38a7.html", null ],
    [ "VERTEX_CONSTANT_BUFFER", "struct_v_e_r_t_e_x___c_o_n_s_t_a_n_t___b_u_f_f_e_r.html", null ],
    [ "mage::VertexPosition", "structmage_1_1_vertex_position.html", null ],
    [ "mage::VertexPositionColor", "structmage_1_1_vertex_position_color.html", null ],
    [ "mage::VertexPositionColorTexture", "structmage_1_1_vertex_position_color_texture.html", null ],
    [ "mage::VertexPositionNormal", "structmage_1_1_vertex_position_normal.html", null ],
    [ "mage::VertexPositionNormalColor", "structmage_1_1_vertex_position_normal_color.html", null ],
    [ "mage::VertexPositionNormalColorTexture", "structmage_1_1_vertex_position_normal_color_texture.html", null ],
    [ "mage::VertexPositionNormalTexture", "structmage_1_1_vertex_position_normal_texture.html", null ],
    [ "mage::VertexPositionTexture", "structmage_1_1_vertex_position_texture.html", null ],
    [ "mage::Viewport", "classmage_1_1_viewport.html", null ],
    [ "mage::Pipeline::VS", "structmage_1_1_pipeline_1_1_v_s.html", null ],
    [ "mage::WireframePass", "classmage_1_1_wireframe_pass.html", null ],
    [ "mage::Writer", "classmage_1_1_writer.html", [
      [ "mage::loader::MDLWriter< VertexT, IndexT >", "classmage_1_1loader_1_1_m_d_l_writer.html", null ],
      [ "mage::loader::VARWriter", "classmage_1_1loader_1_1_v_a_r_writer.html", null ]
    ] ]
];