var namespacemage_1_1rendering =
[
    [ "loader", "namespacemage_1_1rendering_1_1loader.html", "namespacemage_1_1rendering_1_1loader" ],
    [ "AAPass", "classmage_1_1rendering_1_1_a_a_pass.html", "classmage_1_1rendering_1_1_a_a_pass" ],
    [ "AmbientLight", "classmage_1_1rendering_1_1_ambient_light.html", "classmage_1_1rendering_1_1_ambient_light" ],
    [ "BackBufferPass", "classmage_1_1rendering_1_1_back_buffer_pass.html", "classmage_1_1rendering_1_1_back_buffer_pass" ],
    [ "BlobCompiledShader", "classmage_1_1rendering_1_1_blob_compiled_shader.html", "classmage_1_1rendering_1_1_blob_compiled_shader" ],
    [ "BoundingVolumePass", "classmage_1_1rendering_1_1_bounding_volume_pass.html", "classmage_1_1rendering_1_1_bounding_volume_pass" ],
    [ "BufferCompiledShader", "classmage_1_1rendering_1_1_buffer_compiled_shader.html", "classmage_1_1rendering_1_1_buffer_compiled_shader" ],
    [ "BufferLock", "classmage_1_1rendering_1_1_buffer_lock.html", "classmage_1_1rendering_1_1_buffer_lock" ],
    [ "Camera", "classmage_1_1rendering_1_1_camera.html", "classmage_1_1rendering_1_1_camera" ],
    [ "CameraBuffer", "structmage_1_1rendering_1_1_camera_buffer.html", "structmage_1_1rendering_1_1_camera_buffer" ],
    [ "CameraLens", "classmage_1_1rendering_1_1_camera_lens.html", "classmage_1_1rendering_1_1_camera_lens" ],
    [ "CameraSettings", "classmage_1_1rendering_1_1_camera_settings.html", "classmage_1_1rendering_1_1_camera_settings" ],
    [ "ColorString", "classmage_1_1rendering_1_1_color_string.html", "classmage_1_1rendering_1_1_color_string" ],
    [ "CompiledShader", "classmage_1_1rendering_1_1_compiled_shader.html", "classmage_1_1rendering_1_1_compiled_shader" ],
    [ "ConstantBuffer", "classmage_1_1rendering_1_1_constant_buffer.html", "classmage_1_1rendering_1_1_constant_buffer" ],
    [ "DeferredPass", "classmage_1_1rendering_1_1_deferred_pass.html", "classmage_1_1rendering_1_1_deferred_pass" ],
    [ "DepthPass", "classmage_1_1rendering_1_1_depth_pass.html", "classmage_1_1rendering_1_1_depth_pass" ],
    [ "DirectionalLight", "classmage_1_1rendering_1_1_directional_light.html", "classmage_1_1rendering_1_1_directional_light" ],
    [ "DirectionalLightBuffer", "structmage_1_1rendering_1_1_directional_light_buffer.html", "structmage_1_1rendering_1_1_directional_light_buffer" ],
    [ "DisplayConfiguration", "classmage_1_1rendering_1_1_display_configuration.html", "classmage_1_1rendering_1_1_display_configuration" ],
    [ "DisplayConfigurator", "classmage_1_1rendering_1_1_display_configurator.html", "classmage_1_1rendering_1_1_display_configurator" ],
    [ "Fog", "classmage_1_1rendering_1_1_fog.html", "classmage_1_1rendering_1_1_fog" ],
    [ "ForwardPass", "classmage_1_1rendering_1_1_forward_pass.html", "classmage_1_1rendering_1_1_forward_pass" ],
    [ "Glyph", "structmage_1_1rendering_1_1_glyph.html", "structmage_1_1rendering_1_1_glyph" ],
    [ "is_shader", "structmage_1_1rendering_1_1is__shader.html", null ],
    [ "is_shader< ComputeShader >", "structmage_1_1rendering_1_1is__shader_3_01_compute_shader_01_4.html", null ],
    [ "is_shader< DomainShader >", "structmage_1_1rendering_1_1is__shader_3_01_domain_shader_01_4.html", null ],
    [ "is_shader< GeometryShader >", "structmage_1_1rendering_1_1is__shader_3_01_geometry_shader_01_4.html", null ],
    [ "is_shader< HullShader >", "structmage_1_1rendering_1_1is__shader_3_01_hull_shader_01_4.html", null ],
    [ "is_shader< PixelShader >", "structmage_1_1rendering_1_1is__shader_3_01_pixel_shader_01_4.html", null ],
    [ "is_shader< VertexShader >", "structmage_1_1rendering_1_1is__shader_3_01_vertex_shader_01_4.html", null ],
    [ "LBufferPass", "classmage_1_1rendering_1_1_l_buffer_pass.html", "classmage_1_1rendering_1_1_l_buffer_pass" ],
    [ "LightBuffer", "structmage_1_1rendering_1_1_light_buffer.html", "structmage_1_1rendering_1_1_light_buffer" ],
    [ "Manager", "classmage_1_1rendering_1_1_manager.html", "classmage_1_1rendering_1_1_manager" ],
    [ "Material", "classmage_1_1rendering_1_1_material.html", "classmage_1_1rendering_1_1_material" ],
    [ "Mesh", "classmage_1_1rendering_1_1_mesh.html", "classmage_1_1rendering_1_1_mesh" ],
    [ "MeshDescriptor", "classmage_1_1rendering_1_1_mesh_descriptor.html", "classmage_1_1rendering_1_1_mesh_descriptor" ],
    [ "Model", "classmage_1_1rendering_1_1_model.html", "classmage_1_1rendering_1_1_model" ],
    [ "ModelBuffer", "structmage_1_1rendering_1_1_model_buffer.html", "structmage_1_1rendering_1_1_model_buffer" ],
    [ "ModelDescriptor", "classmage_1_1rendering_1_1_model_descriptor.html", "classmage_1_1rendering_1_1_model_descriptor" ],
    [ "ModelOutput", "structmage_1_1rendering_1_1_model_output.html", "structmage_1_1rendering_1_1_model_output" ],
    [ "ModelPart", "structmage_1_1rendering_1_1_model_part.html", "structmage_1_1rendering_1_1_model_part" ],
    [ "OmniLight", "classmage_1_1rendering_1_1_omni_light.html", "classmage_1_1rendering_1_1_omni_light" ],
    [ "OmniLightBuffer", "structmage_1_1rendering_1_1_omni_light_buffer.html", "structmage_1_1rendering_1_1_omni_light_buffer" ],
    [ "OrthographicCamera", "classmage_1_1rendering_1_1_orthographic_camera.html", "classmage_1_1rendering_1_1_orthographic_camera" ],
    [ "OutputManager", "classmage_1_1rendering_1_1_output_manager.html", "classmage_1_1rendering_1_1_output_manager" ],
    [ "PerspectiveCamera", "classmage_1_1rendering_1_1_perspective_camera.html", "classmage_1_1rendering_1_1_perspective_camera" ],
    [ "Pipeline", "structmage_1_1rendering_1_1_pipeline.html", "structmage_1_1rendering_1_1_pipeline" ],
    [ "PointLightBuffer", "structmage_1_1rendering_1_1_point_light_buffer.html", "structmage_1_1rendering_1_1_point_light_buffer" ],
    [ "PostProcessPass", "classmage_1_1rendering_1_1_post_process_pass.html", "classmage_1_1rendering_1_1_post_process_pass" ],
    [ "PrimitiveBatchMesh", "classmage_1_1rendering_1_1_primitive_batch_mesh.html", "classmage_1_1rendering_1_1_primitive_batch_mesh" ],
    [ "Renderer", "classmage_1_1rendering_1_1_renderer.html", "classmage_1_1rendering_1_1_renderer" ],
    [ "ResourceManager", "classmage_1_1rendering_1_1_resource_manager.html", "classmage_1_1rendering_1_1_resource_manager" ],
    [ "SecondaryCameraBuffer", "structmage_1_1rendering_1_1_secondary_camera_buffer.html", "structmage_1_1rendering_1_1_secondary_camera_buffer" ],
    [ "Shader", "classmage_1_1rendering_1_1_shader.html", "classmage_1_1rendering_1_1_shader" ],
    [ "ShadowCubeMapBuffer", "classmage_1_1rendering_1_1_shadow_cube_map_buffer.html", "classmage_1_1rendering_1_1_shadow_cube_map_buffer" ],
    [ "ShadowMapBuffer", "classmage_1_1rendering_1_1_shadow_map_buffer.html", "classmage_1_1rendering_1_1_shadow_map_buffer" ],
    [ "ShadowMappedOmniLightBuffer", "structmage_1_1rendering_1_1_shadow_mapped_omni_light_buffer.html", "structmage_1_1rendering_1_1_shadow_mapped_omni_light_buffer" ],
    [ "ShadowMappedSpotLightBuffer", "structmage_1_1rendering_1_1_shadow_mapped_spot_light_buffer.html", "structmage_1_1rendering_1_1_shadow_mapped_spot_light_buffer" ],
    [ "Sky", "classmage_1_1rendering_1_1_sky.html", "classmage_1_1rendering_1_1_sky" ],
    [ "SkyPass", "classmage_1_1rendering_1_1_sky_pass.html", "classmage_1_1rendering_1_1_sky_pass" ],
    [ "SpotLight", "classmage_1_1rendering_1_1_spot_light.html", "classmage_1_1rendering_1_1_spot_light" ],
    [ "SpotLightBuffer", "structmage_1_1rendering_1_1_spot_light_buffer.html", "structmage_1_1rendering_1_1_spot_light_buffer" ],
    [ "SpriteBatch", "classmage_1_1rendering_1_1_sprite_batch.html", "classmage_1_1rendering_1_1_sprite_batch" ],
    [ "SpriteBatchMesh", "classmage_1_1rendering_1_1_sprite_batch_mesh.html", "classmage_1_1rendering_1_1_sprite_batch_mesh" ],
    [ "SpriteFont", "classmage_1_1rendering_1_1_sprite_font.html", "classmage_1_1rendering_1_1_sprite_font" ],
    [ "SpriteFontDescriptor", "classmage_1_1rendering_1_1_sprite_font_descriptor.html", "classmage_1_1rendering_1_1_sprite_font_descriptor" ],
    [ "SpriteFontOutput", "structmage_1_1rendering_1_1_sprite_font_output.html", "structmage_1_1rendering_1_1_sprite_font_output" ],
    [ "SpriteImage", "classmage_1_1rendering_1_1_sprite_image.html", "classmage_1_1rendering_1_1_sprite_image" ],
    [ "SpritePass", "classmage_1_1rendering_1_1_sprite_pass.html", "classmage_1_1rendering_1_1_sprite_pass" ],
    [ "SpriteText", "classmage_1_1rendering_1_1_sprite_text.html", "classmage_1_1rendering_1_1_sprite_text" ],
    [ "StateManager", "classmage_1_1rendering_1_1_state_manager.html", "classmage_1_1rendering_1_1_state_manager" ],
    [ "StaticMesh", "classmage_1_1rendering_1_1_static_mesh.html", "classmage_1_1rendering_1_1_static_mesh" ],
    [ "StructuredBuffer", "classmage_1_1rendering_1_1_structured_buffer.html", "classmage_1_1rendering_1_1_structured_buffer" ],
    [ "SwapChain", "classmage_1_1rendering_1_1_swap_chain.html", "classmage_1_1rendering_1_1_swap_chain" ],
    [ "Texture", "classmage_1_1rendering_1_1_texture.html", "classmage_1_1rendering_1_1_texture" ],
    [ "VertexPosition", "structmage_1_1rendering_1_1_vertex_position.html", "structmage_1_1rendering_1_1_vertex_position" ],
    [ "VertexPositionColor", "structmage_1_1rendering_1_1_vertex_position_color.html", "structmage_1_1rendering_1_1_vertex_position_color" ],
    [ "VertexPositionColorTexture", "structmage_1_1rendering_1_1_vertex_position_color_texture.html", "structmage_1_1rendering_1_1_vertex_position_color_texture" ],
    [ "VertexPositionNormal", "structmage_1_1rendering_1_1_vertex_position_normal.html", "structmage_1_1rendering_1_1_vertex_position_normal" ],
    [ "VertexPositionNormalColor", "structmage_1_1rendering_1_1_vertex_position_normal_color.html", "structmage_1_1rendering_1_1_vertex_position_normal_color" ],
    [ "VertexPositionNormalColorTexture", "structmage_1_1rendering_1_1_vertex_position_normal_color_texture.html", "structmage_1_1rendering_1_1_vertex_position_normal_color_texture" ],
    [ "VertexPositionNormalTexture", "structmage_1_1rendering_1_1_vertex_position_normal_texture.html", "structmage_1_1rendering_1_1_vertex_position_normal_texture" ],
    [ "VertexPositionTexture", "structmage_1_1rendering_1_1_vertex_position_texture.html", "structmage_1_1rendering_1_1_vertex_position_texture" ],
    [ "VertexShader", "classmage_1_1rendering_1_1_vertex_shader.html", "classmage_1_1rendering_1_1_vertex_shader" ],
    [ "Viewport", "classmage_1_1rendering_1_1_viewport.html", "classmage_1_1rendering_1_1_viewport" ],
    [ "VoxelGrid", "classmage_1_1rendering_1_1_voxel_grid.html", "classmage_1_1rendering_1_1_voxel_grid" ],
    [ "VoxelGridPass", "classmage_1_1rendering_1_1_voxel_grid_pass.html", "classmage_1_1rendering_1_1_voxel_grid_pass" ],
    [ "VoxelizationPass", "classmage_1_1rendering_1_1_voxelization_pass.html", "classmage_1_1rendering_1_1_voxelization_pass" ],
    [ "VoxelizationSettings", "classmage_1_1rendering_1_1_voxelization_settings.html", "classmage_1_1rendering_1_1_voxelization_settings" ],
    [ "World", "classmage_1_1rendering_1_1_world.html", "classmage_1_1rendering_1_1_world" ],
    [ "WorldBuffer", "structmage_1_1rendering_1_1_world_buffer.html", "structmage_1_1rendering_1_1_world_buffer" ]
];